services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '54321:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - working_time_docker_pg_data:/bitnami/postgresql

volumes:
  working_time_docker_pg_data:
